SistemaVenda.Web/Controllers/AcessoController.cs
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Mvc;
using SistemaVenda.BLL.Interfaces;
using SistemaVenda.Entity;
using SistemaVenda.Web.ViewModels;
using System.Security.Claims;

namespace SistemaVenda.Web.Controllers
{
    public class AcessoController : Controller
    {
        private readonly IUsuarioService _usuarioService;

        public AcessoController(IUsuarioService usuarioService)
        {
            _usuarioService = usuarioService;
        }

        public IActionResult Login()
        {
            ClaimsPrincipal claimUser = HttpContext.User;

            if (claimUser.Identity.IsAuthenticated)
            {
                return RedirectToAction("Index", "Home");
            }

            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Login(UsuarioLoginViewModel modelo)
        {
            Usuario usuario = await _usuarioService.ObterPorCredenciais(modelo.Email, modelo.Senha);

            if (usuario == null)
            {
                ViewData["Mensagem"] = "Email e/ou senha não conferem";
                return View();
            }

            ViewData["Mensagem"] = null;

            List<Claim> claims = new List<Claim>()
            {
                new Claim(ClaimTypes.Name, usuario.Nome),
                new Claim(ClaimTypes.NameIdentifier, usuario.UsuarioId.ToString()),
                new Claim(ClaimTypes.Role, usuario.RoleId.ToString()),
                new Claim("UrlFoto", usuario.UrlFoto)
            };

            ClaimsIdentity claimsIdentity = new ClaimsIdentity(claims, CookieAuthenticationDefaults.AuthenticationScheme);

            AuthenticationProperties authenticationProperties = new AuthenticationProperties()
            {
                AllowRefresh = true,
                IsPersistent = modelo.ManterSessao,
            };

            await HttpContext.SignInAsync(CookieAuthenticationDefaults.AuthenticationScheme, new ClaimsPrincipal(claimsIdentity), authenticationProperties);

            return RedirectToAction("Index", "DashBoard");
        }

        public IActionResult RestaurarSenha()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> RestaurarSenha(UsuarioLoginViewModel modelo)
        {
            try
            {
                var urlModeloEmail = $"{this.Request.Scheme}://{this.Request.Host}/Modelo/RestaurarSenha?senha={modelo.Senha}";

                var resultado = await _usuarioService.RestaurarSenha(modelo.Email, urlModeloEmail);

                if (resultado)
                {
                    ViewData["Mensagem"] = "Ótimo! Sua senha foi restaurada. Revise seu e-mail";
                    ViewData["MensagemError"] = null;
                }
                else
                {
                    ViewData["MensagemError"] = "Temos um problema. Por favor tente novamente mais tarde";
                    ViewData["Mensagem"] = null;
                }
            }
            catch (Exception ex)
            {
                ViewData["MensagemError"] = ex.Message;
                ViewData["Mensagem"] = null;
            }

            return View();
        }
    }
}

SistemaVenda.Web/Views/Acesso/Login.cshtml
@model SistemaVenda.Web.ViewModels.UsuarioLoginViewModel
@{
    Layout = null;
}

<!DOCTYPE html>
<html lang="pt-br">

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Minha Loja - Login</title>

    <!-- Custom fonts for this template-->
    <link href="~/vendor/fontawesome-free/css/all.min.css" rel="stylesheet" type="text/css">
    <link href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i"
          rel="stylesheet">

    <!-- Custom styles for this template-->
    <link href="~/css/sb-admin-2.css" rel="stylesheet">

</head>

<body class="bg-gradient-info">

    <div class="container">

        <!-- Outer Row -->
        <div class="row justify-content-center">

            <div class="col-xl-10 col-lg-12 col-md-9">

                <div class="card o-hidden border-0 shadow-lg my-5">
                    <div class="card-body p-0">
                        <!-- Nested Row within Card Body -->
                        <div class="row">
                            <div class="col-lg-6 d-none d-lg-block bg-login-image"></div>
                            <div class="col-lg-6">
                                <div class="p-5">
                                    <div class="text-center">
                                        <h1 class="h4 text-gray-900 mb-4">Bem-vindo</h1>
                                    </div>
                                    <form class="user" asp-controller="Acesso" asp-action="Login" method="post">
                                        <div class="form-group">
                                            <input type="email" class="form-control form-control-user" placeholder="Email" asp-for="Email">
                                        </div>
                                        <div class="form-group">
                                            <input type="password" class="form-control form-control-user" placeholder="Senha" asp-for="Senha">
                                        </div>
                                        <div class="form-group">
                                            <div class="custom-control custom-checkbox small">
                                                <input type="checkbox" class="custom-control-input" id="chkManterSessao" asp-for="ManterSessao">
                                                <label class="custom-control-label" for="chkMantenerSesion">Manter Sessão</label>
                                            </div>
                                        </div>

                                        @if (ViewData["Mensagem"] != null)
                                        {
                                                <div class="form-group">
                                                    <div class="alert alert-danger" role="alert">
                                                    @ViewData["Mensagem"]
                                                    </div>
                                                </div>
                                        }

                                        <button type="submit" class="btn btn-primary btn-user btn-block">
                                            Entrar
                                        </button>
                                    </form>
                                    <hr>
                                    <div class="text-center">
                                        <a class="small" href="@Url.Action("RestaurarSenha", "Acesso")">Esqueceu sua senha?</a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>

            </div>

        </div>

    </div>


</body>

</html>

SistemaVenda.Web/Views/Acesso/RestaurarSenha.cshtml
@model SistemaVenda.Web.ViewModels.UsuarioLoginViewModel
@{
    Layout = null;
}

<!DOCTYPE html>
<html lang="pt-br">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Minha Loja - Restaurar Senha</title>

    <!-- Custom fonts for this template-->
    <link href="~/vendor/fontawesome-free/css/all.min.css" rel="stylesheet" type="text/css">
    <link href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i" rel="stylesheet">

    <!-- Custom styles for this template-->
    <link href="~/css/sb-admin-2.css" rel="stylesheet">

</head>

<body class="bg-gradient-info">

    <div class="container">

        <!-- Outer Row -->
        <div class="row justify-content-center">

            <div class="col-xl-10 col-lg-12 col-md-9">

                <div class="card o-hidden border-0 shadow-lg my-5">
                    <div class="card-body p-0">
                        <!-- Nested Row within Card Body -->
                        <div class="row">
                            <div class="col-lg-6 d-none d-lg-block bg-password-image"></div>
                            <div class="col-lg-6">
                                <div class="p-5">
                                    <div class="text-center">
                                        <h1 class="h4 text-gray-900 mb-2">Esqueceu sua senha?</h1>
                                        <p class="mb-4">Digite o e-mail da sua sessão e lhe enviaremos uma nova senha</p>
                                    </div>
                                    <form class="user" asp-controller="Acesso" asp-action="RestaurarSenha" method="post">
                                        <div class="form-group">
                                            <input type="email" class="form-control form-control-user" asp-for="Email" placeholder="Digite seu e-mail">
                                        </div>
                                        @if (ViewData["Mensagem"] != null)
                                        {
                                                <div class="form-group">
                                                    <div class="alert alert-success" role="alert">
                                                    @ViewData["Mensagem"]
                                                    </div>
                                                </div>
                                        }
                                        @if (ViewData["MensagemError"] != null)
                                        {
                                                <div class="form-group">
                                                    <div class="alert alert-danger" role="alert">
                                                    @ViewData["MensagemError"]
                                                    </div>
                                                </div>
                                        }
                                        <button type="submit" class="btn btn-primary btn-user btn-block">
                                            Redefinir senha
                                        </button>
                                    </form>
                                    <hr>
                                    <div class="text-center">
                                        <a class="small" href="@Url.Action("Login", "Acesso")">Iniciar Sessão</a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>

            </div>

        </div>

    </div>

</body>

</html>