SistemaVenda.Web/Controllers/NegocioController.cs
using AutoMapper;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using SistemaVenda.BLL.Interfaces;
using SistemaVenda.Entity;
using SistemaVenda.Web.Utilidades.Response;
using SistemaVenda.Web.ViewModels;

namespace SistemaVenda.Web.Controllers
{
    [Authorize]
    public class NegocioController : Controller
    {
        private readonly IMapper _mapper;
        private readonly INegocioService _negocioService;

        public NegocioController(IMapper mapper, INegocioService negocioService)
        {
            _mapper = mapper;
            _negocioService = negocioService;
        }

        public IActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public async Task<IActionResult> Obter()
        {
            GenericResponse<NegocioViewModel> gResponse = new GenericResponse<NegocioViewModel>();

            try
            {
                var vmNegocio = _mapper.Map<NegocioViewModel>(await _negocioService.Obter());

                gResponse.Estado = true;
                gResponse.Objeto = vmNegocio;
            }
            catch (Exception ex)
            {
                gResponse.Estado = false;
                gResponse.Mensagem = ex.Message;
            }

            return StatusCode(StatusCodes.Status200OK, gResponse);
        }

        [HttpPost]
        public async Task<IActionResult> Salvar([FromForm] IFormFile logo, [FromForm] string modelo)
        {
            GenericResponse<NegocioViewModel> gResponse = new GenericResponse<NegocioViewModel>();

            try
            {
                var vmNegocio = JsonConvert.DeserializeObject<NegocioViewModel>(modelo);

                var nomeLogo = string.Empty;
                Stream logoStream = null!;

                if (logo != null)
                {
                    var nomeEmCodigo = Guid.NewGuid().ToString("N");
                    var extension = Path.GetExtension(logo.FileName);
                    nomeLogo = string.Concat(nomeEmCodigo, extension);
                    logoStream = logo.OpenReadStream();
                }

                var negocio = await _negocioService.Salvar(_mapper.Map<Negocio>(vmNegocio), logoStream, nomeLogo);

                vmNegocio = _mapper.Map<NegocioViewModel>(negocio);

                gResponse.Estado = true;
                gResponse.Objeto = vmNegocio;
            }
            catch (Exception ex)
            {
                gResponse.Estado = false;
                gResponse.Mensagem = ex.Message;
            }

            return StatusCode(StatusCodes.Status200OK, gResponse);
        }
    }
}

SistemaVenda.Web/Controllers/ProdutoController.cs
using AutoMapper;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using SistemaVenda.BLL.Implementacao;
using SistemaVenda.BLL.Interfaces;
using SistemaVenda.Entity;
using SistemaVenda.Web.Utilidades.Response;
using SistemaVenda.Web.ViewModels;

namespace SistemaVenda.Web.Controllers
{
    [Authorize]
    public class ProdutoController : Controller
    {
        
        private readonly IProdutoService _produtoService;
        private readonly ICategoriaService _categoriaService;
        private readonly IMapper _mapper;

        public ProdutoController(IProdutoService produtoService, ICategoriaService categoriaService, IMapper mapper)
        {
            _produtoService = produtoService;
            _categoriaService = categoriaService;
            _mapper = mapper;
        }

        public IActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public async Task<IActionResult> ListaCategorias()
        {
            List<CategoriaViewModel> vmListaCategorias = _mapper.Map<List<CategoriaViewModel>>(await _categoriaService.Lista());

            return StatusCode(StatusCodes.Status200OK, vmListaCategorias);
        }

        [HttpGet]
        public async Task<IActionResult> Lista()
        {
            List<ProdutoViewModel> vmProdutoLista = _mapper.Map<List<ProdutoViewModel>>(await _produtoService.Lista());

            return StatusCode(StatusCodes.Status200OK, new { data = vmProdutoLista });
        }

        [HttpPost]
        public async Task<IActionResult> Criar([FromForm] IFormFile imagem, [FromForm] string modelo)
        {
            GenericResponse<ProdutoViewModel> gResponse = new GenericResponse<ProdutoViewModel>();

            try
            {
                var vmProduto = JsonConvert.DeserializeObject<ProdutoViewModel>(modelo);

                var nomeImagem = string.Empty;
                Stream imagemStream = null!;

                if (imagem != null)
                {
                    var nomeCodigo = Guid.NewGuid().ToString("N");
                    var extensao = Path.GetExtension(imagem.FileName);
                    nomeImagem = string.Concat(nomeCodigo, extensao);
                    imagemStream = imagem.OpenReadStream();
                }

                var produto = await _produtoService.Criar(_mapper.Map<Produto>(vmProduto), imagemStream, nomeImagem);

                vmProduto = _mapper.Map<ProdutoViewModel>(produto);

                gResponse.Estado = true;
                gResponse.Objeto = vmProduto;
            }
            catch (Exception ex)
            {
                gResponse.Estado = false;
                gResponse.Mensagem = ex.Message;
            }

            return StatusCode(StatusCodes.Status200OK, gResponse);
        }

        [HttpPut]
        public async Task<IActionResult> Editar([FromForm] IFormFile imagem, [FromForm] string modelo)
        {
            GenericResponse<ProdutoViewModel> gResponse = new GenericResponse<ProdutoViewModel>();

            try
            {
                var vmProduto = JsonConvert.DeserializeObject<ProdutoViewModel>(modelo);

                var nomeImagem = string.Empty;
                Stream imagemStream = null!;

                if (imagem != null)
                {
                    var nomeCodigo = Guid.NewGuid().ToString("N");
                    var extensao = Path.GetExtension(imagem.FileName);
                    nomeImagem = string.Concat(nomeCodigo, extensao);
                    imagemStream = imagem.OpenReadStream();
                }

                var produto = await _produtoService.Editar(_mapper.Map<Produto>(vmProduto), imagemStream, nomeImagem);

                vmProduto = _mapper.Map<ProdutoViewModel>(produto);

                gResponse.Estado = true;
                gResponse.Objeto = vmProduto;
            }
            catch (Exception ex)
            {
                gResponse.Estado = false;
                gResponse.Mensagem = ex.Message;
            }

            return StatusCode(StatusCodes.Status200OK, gResponse);
        }

        [HttpDelete]
        public async Task<IActionResult> Excluir(int idProduto)
        {
            GenericResponse<string> gResponse = new GenericResponse<string>();

            try
            {
                gResponse.Estado = await _produtoService.Excluir(idProduto);
            }
            catch (Exception ex)
            {
                gResponse.Estado = false;
                gResponse.Mensagem = ex.Message;
            }

            return StatusCode(StatusCodes.Status200OK, gResponse);
        }
    }
}

SistemaVenda.Web/Controllers/UsuarioController.cs
using AutoMapper;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using SistemaVenda.BLL.Interfaces;
using SistemaVenda.Entity;
using SistemaVenda.Web.Utilidades.Response;
using SistemaVenda.Web.ViewModels;

namespace SistemaVenda.Web.Controllers
{
    [Authorize]
    public class UsuarioController : Controller
    {
        private readonly IUsuarioService _usuarioService;
        private readonly IRoleService _roleService;
        private readonly IMapper _mapper;

        public UsuarioController(IUsuarioService usuarioService, IRoleService roleService, IMapper mapper)
        {
            _usuarioService = usuarioService;
            _roleService = roleService;
            _mapper = mapper;
        }

        public IActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public async Task<IActionResult> ListaRoles()
        {
            List<RoleViewModel> vmListaRoles = _mapper.Map<List<RoleViewModel>>(await _roleService.Lista());

            return StatusCode(StatusCodes.Status200OK, vmListaRoles);
        }

        [HttpGet]
        public async Task<IActionResult> Lista()
        {
            List<UsuarioViewModel> vmListaUsuarios = _mapper.Map<List<UsuarioViewModel>>(await _usuarioService.Lista());

            return StatusCode(StatusCodes.Status200OK, new { data = vmListaUsuarios });
        }

        [HttpPost]
        public async Task<IActionResult> Criar([FromForm] IFormFile foto, [FromForm] string modelo)
        {
            GenericResponse<UsuarioViewModel> gResponse = new GenericResponse<UsuarioViewModel>();

            try
            {
                UsuarioViewModel vmUsuario = JsonConvert.DeserializeObject<UsuarioViewModel>(modelo);

                var nomeFoto = string.Empty;
                Stream fotoStream = null;

                if (foto != null)
                {
                    var nomeEmCodigo = Guid.NewGuid().ToString("N");
                    var extensao = Path.GetExtension(foto.FileName);
                    nomeFoto = string.Concat(nomeEmCodigo, extensao);
                    fotoStream = foto.OpenReadStream();
                }

                var urlModeloEmail = $"{this.Request.Scheme}://{this.Request.Host}/Modelo/EnviarSenha?email=[email]&senha=[senha]";

                Usuario usuario = await _usuarioService.Criar(_mapper.Map<Usuario>(vmUsuario), fotoStream, nomeFoto, urlModeloEmail);

                vmUsuario = _mapper.Map<UsuarioViewModel>(usuario);

                gResponse.Estado = true;
                gResponse.Objeto = vmUsuario;
            }
            catch (Exception ex)
            {
                gResponse.Estado = false;
                gResponse.Mensagem = ex.Message;
            }

            return StatusCode(StatusCodes.Status200OK, gResponse);
        }

        [HttpPut]
        public async Task<IActionResult> Editar([FromForm] IFormFile foto, [FromForm] string modelo)
        {
            GenericResponse<UsuarioViewModel> gResponse = new GenericResponse<UsuarioViewModel>();

            try
            {
                UsuarioViewModel vmUsuario = JsonConvert.DeserializeObject<UsuarioViewModel>(modelo);

                var nomeFoto = string.Empty;
                Stream fotoStream = null;

                if (foto != null)
                {
                    var nomeEmCodigo = Guid.NewGuid().ToString("N");
                    var extensao = Path.GetExtension(foto.FileName);
                    nomeFoto = string.Concat(nomeEmCodigo, extensao);
                    fotoStream = foto.OpenReadStream();
                }

                Usuario usuario = await _usuarioService.Editar(_mapper.Map<Usuario>(vmUsuario), fotoStream, nomeFoto);

                vmUsuario = _mapper.Map<UsuarioViewModel>(usuario);

                gResponse.Estado = true;
                gResponse.Objeto = vmUsuario;
            }
            catch (Exception ex)
            {
                gResponse.Estado = false;
                gResponse.Mensagem = ex.Message;
            }

            return StatusCode(StatusCodes.Status200OK, gResponse);
        }

        [HttpDelete]
        public async Task<IActionResult> Excluir(int idUsuario)
        {
            GenericResponse<string> gResponse = new GenericResponse<string>();

            try
            {
                gResponse.Estado = await _usuarioService.Excluir(idUsuario);
            }
            catch (Exception ex)
            {
                gResponse.Estado = false;
                gResponse.Mensagem = ex.Message;
            }

            return StatusCode(StatusCodes.Status200OK, gResponse);
        }
    }
}

SistemaVenda.Web/Controllers/VendaController.cs
using AutoMapper;
using DinkToPdf;
using DinkToPdf.Contracts;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using SistemaVenda.BLL.Interfaces;
using SistemaVenda.Entity;
using SistemaVenda.Web.Utilidades.Response;
using SistemaVenda.Web.ViewModels;
using System.Security.Claims;

namespace SistemaVenda.Web.Controllers
{
    [Authorize]
    public class VendaController : Controller
    {
        private readonly ITipoDocumentoVendaService _tipoDocumentoVendaService;
        private readonly IVendaService _vendaService;
        private readonly IMapper _mapper;
        private readonly IConverter _converter;

        public VendaController(ITipoDocumentoVendaService tipoDocumentoVendaService, IVendaService vendaService, IMapper mapper, IConverter converter)
        {
            _tipoDocumentoVendaService = tipoDocumentoVendaService;
            _vendaService = vendaService;
            _mapper = mapper;
            _converter = converter;
        }

        public IActionResult NovaVenda()
        {
            return View();
        }

        public IActionResult HistoricoVendas()
        {
            return View();
        }

        [HttpGet]
        public async Task<IActionResult> ListaTipoDocumentoVenda()
        {
            List<TipoDocumentoVendaViewModel> vmListaTipoDocumentos = _mapper.Map<List<TipoDocumentoVendaViewModel>>(await _tipoDocumentoVendaService.Lista());

            return StatusCode(StatusCodes.Status200OK, vmListaTipoDocumentos);
        }

        [HttpGet]
        public async Task<IActionResult> ObterProdutos(string buscar)
        {
            List<ProdutoViewModel> vmListaProdutos = _mapper.Map<List<ProdutoViewModel>>(await _vendaService.ObterProdutos(buscar));

            return StatusCode(StatusCodes.Status200OK, vmListaProdutos);
        }

        [HttpPost]
        public async Task<IActionResult> CriarVenda([FromBody] VendaViewModel modelo)
        {
            GenericResponse<VendaViewModel> gResponse = new GenericResponse<VendaViewModel>();

            try
            {
                ClaimsPrincipal claimUser = HttpContext.User;

                var usuarioId = claimUser.Claims
                    .Where(c => c.Type == ClaimTypes.NameIdentifier)
                    .Select(c => c.Value)
                    .SingleOrDefault();

                modelo.UsuarioId = int.Parse(usuarioId);

                var venda = await _vendaService.Criar(_mapper.Map<Venda>(modelo));
                modelo = _mapper.Map<VendaViewModel>(venda);

                gResponse.Estado = true;
                gResponse.Objeto = modelo;
            }
            catch (Exception ex)
            {
                gResponse.Estado = false;
                gResponse.Mensagem = ex.Message;
            }

            return StatusCode(StatusCodes.Status200OK, gResponse);
        }

        [HttpGet]
        public async Task<IActionResult> Historico(string numeroVenda, string dataInicio, string dataFim)
        {
            List<VendaViewModel> vmHistoricoVendaLista = _mapper.Map<List<VendaViewModel>>(await _vendaService.Historico(numeroVenda, dataInicio, dataFim));

            return StatusCode(StatusCodes.Status200OK, vmHistoricoVendaLista);
        }

        public IActionResult MostrarPDFVenda(string numeroVenda)
        {
            var urlModelo = $"{this.Request.Scheme}://{this.Request.Host}/Modelo/PDFVenda?numeroVenda={numeroVenda}";

            var pdf = new HtmlToPdfDocument()
            {
                GlobalSettings = new GlobalSettings()
                {
                    PaperSize = PaperKind.A4,
                    Orientation = Orientation.Portrait,
                },
                Objects =
                {
                    new ObjectSettings()
                    {
                        Page = urlModelo
                    }
                }
            };

            var arquivoPDF = _converter.Convert(pdf);

            return File(arquivoPDF, "application/pdf");
        }
    }
}

SistemaVenda.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="Erismar Oliveira">

    <title>Minha Loja - @ViewData["Title"]</title>

    <!-- Custom fonts for this template-->
    <link href="~/vendor/fontawesome-free/css/all.min.css" rel="stylesheet" type="text/css">
    <link href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i" rel="stylesheet">

    <!-- Custom styles for this template-->
    <link href="~/css/sb-admin-2.css" rel="stylesheet">
    <link href="~/vendor/toastr/toastr.min.css" rel="stylesheet">
    <link href="~/vendor/sweetalert/sweetalert.css" rel="stylesheet">
    @await RenderSectionAsync("Estilos", required: false)
</head>
<body id="page-top">

    <!-- Page Wrapper -->
    <div id="wrapper">

        <!-- Sidebar -->
        <ul class="navbar-nav bg-gradient-primary sidebar sidebar-dark accordion" id="accordionSidebar">

            <!-- Sidebar - Brand -->
            <a class="sidebar-brand d-flex align-items-center justify-content-center" href="#">
                <div class="sidebar-brand-icon">
                    <i class="fas fa-desktop"></i>
                </div>
                <div class="sidebar-brand-text mx-3">MINHA LOJA</div>
            </a>

            <!-- Divider -->
            <hr class="sidebar-divider my-0">

            @await Component.InvokeAsync("Menu")

            <!-- Nav Item - Dashboard -->
            @* <li class="nav-item">
                <a class="nav-link" href="@Url.Action("Index", "DashBoard")">
                    <i class="fas fa-fw fa-tachometer-alt"></i>
                    <span>Dashboard</span>
                </a>
            </li> *@

            <!-- Nav Item - Administração Collapse Menu -->
            @* <li class="nav-item">
                <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseAdministracao">
                    <i class="fas fa-fw fa-cog"></i>
                    <span>Administração</span>
                </a>
                <div id="collapseAdministracao" class="collapse" data-parent="#accordionSidebar">
                    <div class="bg-white py-2 collapse-inner rounded">
                        <a class="collapse-item" href="@Url.Action("Index", "Usuario")">Usuários</a>
                        <a class="collapse-item" href="@Url.Action("Index", "Negocio")">Negócio</a>
                    </div>
                </div>
            </li> *@

            <!-- Nav Item - Inventário Collapse Menu -->
            @* <li class="nav-item">
                <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseInventario">
                    <i class="fas fa-fw fa-clipboard-list"></i>
                    <span>Inventário</span>
                </a>
                <div id="collapseInventario" class="collapse" data-parent="#accordionSidebar">
                    <div class="bg-white py-2 collapse-inner rounded">
                        <a class="collapse-item" href="@Url.Action("Index", "Categoria")">Categorias</a>
                        <a class="collapse-item" href="@Url.Action("Index", "Produto")">Produtos</a>
                    </div>
                </div>
            </li> *@

            <!-- Nav Item - Venda Collapse Menu -->
            @* <li class="nav-item">
                <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseVenda">
                    <i class="fas fa-fw fa-tags"></i>
                    <span>Vendas</span>
                </a>
                <div id="collapseVenda" class="collapse" data-parent="#accordionSidebar">
                    <div class="bg-white py-2 collapse-inner rounded">
                        <a class="collapse-item" href="@Url.Action("NovaVenda", "Venda")">Nova Venda</a>
                        <a class="collapse-item" href="@Url.Action("HistoricoVenda", "Venda")">Histórico de Vendas</a>
                    </div>
                </div>
            </li> *@

            <!-- Nav Item - Relatórios Collapse Menu -->
            @* <li class="nav-item">
                <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseRelatorios">
                    <i class="fas fa-fw fa-chart-area"></i>
                    <span>Relatórios</span>
                </a>
                <div id="collapseRelatorios" class="collapse" data-parent="#accordionSidebar">
                    <div class="bg-white py-2 collapse-inner rounded">
                        <a class="collapse-item" href="@Url.Action("Index", "Relatorio")">Relatório de Vendas</a>
                    </div>
                </div>
            </li> *@

            <!-- Divider -->
            <hr class="sidebar-divider">
            <!-- Sidebar Toggler (Sidebar) -->
            <div class="text-center d-none d-md-inline">
                <button class="rounded-circle border-0" id="sidebarToggle"></button>
            </div>
        </ul>
        <!-- End of Sidebar -->
        <!-- Content Wrapper -->
        <div id="content-wrapper" class="d-flex flex-column">

            <!-- Main Content -->
            <div id="content">

                <!-- Topbar -->
                <nav class="navbar navbar-expand navbar-light bg-white topbar mb-4 static-top shadow">

                    <!-- Sidebar Toggle (Topbar) -->
                    <button id="sidebarToggleTop" class="btn btn-link d-md-none rounded-circle mr-3">
                        <i class="fa fa-bars"></i>
                    </button>

                    <!-- Topbar Navbar -->
                    <ul class="navbar-nav ml-auto">

                        <div class="topbar-divider d-none d-sm-block"></div>

                        @* <!-- Nav Item - User Information -->
                        <li class="nav-item dropdown no-arrow">
                            <a class="nav-link dropdown-toggle" href="#" id="userDropdown" role="button"
                               data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                <span class="mr-2 d-none d-lg-inline text-gray-600 small">Douglas McGee</span>
                                <img class="img-profile rounded-circle"
                                     src="https://images.unsplash.com/photo-1519648023493-d82b5f8d7b8a?w=300">
                            </a>
                            <!-- Dropdown - User Information -->
                            <div class="dropdown-menu dropdown-menu-right shadow animated--grow-in"
                                 aria-labelledby="userDropdown">
                                <a class="dropdown-item" href="@Url.Action("Perfil", "Home")">
                                    <i class="fas fa-user fa-sm fa-fw mr-2 text-gray-400"></i>
                                    Perfil
                                </a>
                                <div class="dropdown-divider"></div>
                                <a class="dropdown-item" href="#" data-toggle="modal" data-target="#logoutModal">
                                    <i class="fas fa-sign-out-alt fa-sm fa-fw mr-2 text-gray-400"></i>
                                    Sair
                                </a>
                            </div>
                        </li> *@

                        @await Component.InvokeAsync("MenuUsuario")

                    </ul>

                </nav>
                <!-- End of Topbar -->
                <!-- Begin Page Content -->
                <div class="container-fluid">
                    @RenderBody()
                </div>
                <!-- /.container-fluid -->

            </div>
            <!-- End of Main Content -->
            <!-- Footer -->
            <footer class="sticky-footer bg-white">
                <div class="container my-auto">
                    <div class="copyright text-center my-auto">
                        <span>Copyright &copy; Your Website @DateTime.Now.Year</span>
                    </div>
                </div>
            </footer>
            <!-- End of Footer -->

        </div>
        <!-- End of Content Wrapper -->

    </div>
    <!-- End of Page Wrapper -->
    <!-- Bootstrap core JavaScript-->
    <script src="~/vendor/jquery/jquery.min.js"></script>
    <script src="~/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>

    <!-- Core plugin JavaScript-->
    <script src="~/vendor/jquery-easing/jquery.easing.min.js"></script>

    <!-- Custom scripts for all pages-->
    <script src="~/js/sb-admin-2.js"></script>
    <script src="~/vendor/toastr/toastr.min.js"></script>
    <script src="~/vendor/sweetalert/sweetalert.js"></script>
    <script src="~/vendor/loadingoverlay/loadingoverlay.min.js"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>